openapi: 3.2.0
info:
  title: Mend Red Team API
  description: Mend's enhanced API enables automation of workflows in a REST compliant format.
  version: '3.0'
servers:
- url: https://baseUrl
  description: Generated server url
security:
- bearer-key: []
tags:
- name: Red Team
paths:
  /api/v3.0/projects/{projectUuid}/ai/redteam/trigger:
    post:
      security:
      - bearer-key: []
      description: Triggers a test run.
      tags:
      - Red Team
      summary: Trigger test run
      operationId: triggerTestRun
      parameters:
      - description: UUID of the project
        name: projectUuid
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v3.V3TestRunTriggerRequest'
        description: Test run trigger configuration
        required: true
      responses:
        '200':
          description: Test run triggered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v3.V3BaseResponse-v3_V3TestRunTriggerResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    v3.V3TestRunTriggerRequest:
      type: object
      required:
      - name
      - targetId
      - probeIds
      properties:
        name:
          type: string
          description: Name of the test run
        targetId:
          type: integer
          description: Target ID for the test run
        probeIds:
          type: array
          description: List of probe IDs to run
          minItems: 1
          items:
            type: integer
    v3.V3TestRunTriggerResponse:
      type: object
      properties:
        testRunId:
          type: integer
          description: ID of the triggered test run
    v3.V3BaseResponse-v3_V3TestRunTriggerResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/v3.V3TestRunTriggerResponse'
        supportToken:
          type: string
  securitySchemes:
    bearer-key:
      type: http
      description: JWT token Bearer
      scheme: bearer
      bearerFormat: JWT
