openapi: 3.0.1
info:
  title: Mend Access Management Administration - Users API
  description: 'Mend''s enhanced API enables automation of workflows in a REST compliant format. The API features:

    + Access for any user with Mend credentials, via a user key available in the user''s profile page in the Mend Platform.

    + Improved security with a JWT token per organization, which expires every 10 minutes.

    + Added scalability with support for cursor pagination and limiting results size.

    + Broader functionality available programmatically.

    + New standard API documentation for easy navigation and search.


    **Note:** To help you get started with the Mend API 3.0, we recommend reviewing our onboarding guide -> [Getting Started with API 3.0](https://docs.mend.io/platform/latest/getting-started-with-mend-api-3-0).

    This resource covers initial setup, authentication instructions, and helpful tips to help you successfully begin working with the Mend API 3.0. If you have a dedicated instance of Mend, contact your Mend representative to access this API on your instance.'
  version: '3.0'
servers:
- url: https://baseUrl
  description: Generated server url
security:
- bearer-key: []
tags:
- name: Administration - Users
paths:
  /api/v3.0/orgs/{orgUuid}/users:
    get:
      tags:
      - Administration - Users
      summary: Get Organization Users
      description: Returns a list of all users in an organization (paginated)
      operationId: getUsersPaginated
      parameters:
      - name: cursor
        in: query
        description: Parameter indicates the starting point for retrieving results, the first call doesn't include a cursor parameter in the request, the API response includes the first set of results along with a cursor pointing to the last item retrieved.
        allowEmptyValue: true
        schema:
          type: string
      - name: limit
        in: query
        description: Specifies the maximum number of items to be returned in the response.
        allowEmptyValue: true
        schema:
          maximum: 10000
          type: string
          default: '50'
      - name: orgUuid
        in: path
        description: 'org UUID (from the Mend App: **Administration** General > **Organization UUID**).'
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DWRResponsePageableV3ListUserInfoDTOV3'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DWRResponseBase'
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DWRResponseBase'
  /api/v3.0/orgs/{orgUuid}/users/invite:
    post:
      tags:
      - Administration - Users
      summary: Invite User
      description: Sends an email invitation to others to join an organization
      operationId: inviteUser
      parameters:
      - name: orgUuid
        in: path
        description: 'org UUID (from the Mend App: **Administration** General > **Organization UUID**).'
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InviteUserRequestDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DWRResponseV3UserInfoResponseDTO'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DWRResponseBase'
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DWRResponseBase'
  /api/v3.0/orgs/{orgUuid}/users/{userUuid}:
    delete:
      tags:
      - Administration - Users
      summary: Remove User From Organization
      description: Deletes a user from an organization
      operationId: removeUser
      parameters:
      - name: orgUuid
        in: path
        description: 'org UUID (from the Mend App: **Administration** General > **Organization UUID**).'
        required: true
        schema:
          type: string
      - name: userUuid
        in: path
        description: User UUID (Administration > Users)
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DWRResponseV3MessageDTO'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DWRResponseBase'
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DWRResponseBase'
  /api/v3.0/orgs/{orgUuid}/users/{userUuid}/block:
    put:
      tags:
      - Administration - Users
      summary: Block User
      description: Blocks a user in the organization
      operationId: blockUser
      parameters:
      - name: orgUuid
        in: path
        description: 'org UUID (from the Mend App: **Administration** General > **Organization UUID**).'
        required: true
        schema:
          type: string
      - name: userUuid
        in: path
        description: User UUID (Administration > Users)
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DWRResponseV3Boolean'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DWRResponseBase'
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DWRResponseBase'
  /api/v3.0/orgs/{orgUuid}/users/{userUuid}/unblock:
    put:
      tags:
      - Administration - Users
      summary: Unblock User
      description: Unblocks a user in the organization
      operationId: unblockUser
      parameters:
      - name: orgUuid
        in: path
        description: 'org UUID (from the Mend App: **Administration** General > **Organization UUID**).'
        required: true
        schema:
          type: string
      - name: userUuid
        in: path
        description: User UUID (Administration > Users)
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DWRResponseV3Boolean'
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DWRResponseBase'
        '403':
          description: Forbidden
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DWRResponseBase'
components:
  schemas:
    InviteUserRequestDTO:
      required:
      - email
      type: object
      properties:
        email:
          title: New User Email
          type: string
          example: jon.smith@mail.com
    UserInfoResponseDTO:
      required:
      - uuid
      type: object
      properties:
        uuid:
          title: User UUID
          type: string
          example: 123e4567-e89b-12d3-a456-426655440000
        name:
          title: User Name
          type: string
          example: Jon Smith
        email:
          title: User Email
          type: string
          example: jon.smith@mail.com
        userType:
          title: Type Of User
          type: string
          example: REGULAR
          enum:
          - REGULAR
          - SERVICE
          - SCAN_SUMMARY_RECEIVER
        existsInOrg:
          type: boolean
    UserInfoDTOV3:
      required:
      - uuid
      type: object
      properties:
        uuid:
          title: User UUID
          type: string
          example: 123e4567-e89b-12d3-a456-426655440000
        name:
          title: User Name
          type: string
          example: Jon Smith
        email:
          title: User Email
          type: string
          example: jon.smith@mail.com
        userType:
          title: Type Of User
          type: string
          example: REGULAR
          enum:
          - REGULAR
          - SERVICE
          - SCAN_SUMMARY_RECEIVER
        accountStatus:
          title: User Account Status
          type: string
          example: ACTIVE
          enum:
          - ACTIVE
          - INVITED
          - DISABLED
    DWRResponseV3UserInfoResponseDTO:
      type: object
      properties:
        supportToken:
          title: Support Token
          type: string
          example: 1171c60d
        response:
          $ref: '#/components/schemas/UserInfoResponseDTO'
    MessageDTO:
      type: object
      properties:
        message:
          title: message
          type: string
          example: Success!
    DWRResponseBase:
      type: object
      properties:
        supportToken:
          title: Support Token
          type: string
          example: 1171c60d
    DWRResponseV3Boolean:
      type: object
      properties:
        supportToken:
          title: Support Token
          type: string
          example: 1171c60d
        response:
          type: boolean
    DWRResponseV3MessageDTO:
      type: object
      properties:
        supportToken:
          title: Support Token
          type: string
          example: 1171c60d
        response:
          $ref: '#/components/schemas/MessageDTO'
    DWRResponsePageableV3ListUserInfoDTOV3:
      type: object
      properties:
        additionalData:
          title: Provides insights into endpoint-supported pagination information.
          type: object
          description: '+ **totalItems**: The total count of data points returned in an API response.

            '
          example:
            totalItems: '422'
            next: http://someUrl?cursor=3
            cursor: 3
        supportToken:
          title: Support Token
          type: string
          example: 1171c60d
        response:
          type: array
          items:
            $ref: '#/components/schemas/UserInfoDTOV3'
  securitySchemes:
    bearer-key:
      type: http
      description: JWT token Bearer
      scheme: bearer
      bearerFormat: JWT
